#!/bin/sh

# Build optimized client release in the `dist` folder using Parcel.
# Deploy to GitHub Pages by pushing to the `master` branch.

set -e

cd ./client

rm -rf ./dist
parcel build ./index.html --public-url ./
cp -r ./assets ./dist/assets
